server:
  port: 9090
spring:
  application:
    #应用的名称，可选
    name: WYZCommunityManagement
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wyzcms?characterEncoding=utf-8&useSSL=false
      username: root
      password: 1234
  servlet:
    multipart:
      max-file-size: 20MB  #图片视频限制为20mb
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true  #允许datasource这个bean被重复定义
  redis:
    host: localhost
    port: 6379
    password: 1234
    lettuce: #连接池配置
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  cache:
    redis:
      time-to-live: 1800000
    type: redis
    cache-names: wyzCache

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #这个可以帮忙打印mp运行时的sql日志
  global-config:
    db-config:
      id-type: ASSIGN_ID
#mybatis:
#  config-location: classpath:mybatis-config.xml

WYZCommunityManagementSystem:
  picturePath: D:/WYZCommunityManagementSystem/resources/picture/
  videoPath: D:/WYZCommunityManagementSystem/resources/video/


#  shardingsphere:
#    datasource:
#      names:
#        master,slave
#      # 主数据源
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.64.100:3306/bms?characterEncoding=utf-8&useSSL=false
#        username: root
#        password: 1234
#      # 从数据源
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.64.101:3306/bms?characterEncoding=utf-8&useSSL=false
#        username: root
#        password: 1234
#    masterslave:
#      # 读写分离配置
#      load-balance-algorithm-type: round_robin
#      # 最终的数据源名称
#      name: dataSource
#      # 主库数据源名称
#      master-data-source-name: master
#      # 从库数据源名称列表，多个逗号分隔
#      slave-data-source-names: slave
#    props:
#      sql:
#        show: true #开启SQL显示，默认false
#  main:
#    allow-bean-definition-overriding: true